# Place your use-case specific settings overrides here.

simulation:
    # name this simulation
    name: mosartwmpy demo
    # path to a directory for writing output files; will be created if doesn't exist
    output_path: ./output
    # date to begin the simulation
    start_date: 1981-05-01
    # date to end the simulation
    end_date: 1981-05-30

grid:
  path: ./input/domains/mosart.nc
  land:
    path: ./input/domains/land.nc

runoff:
  read_from_file: true
  path: ./input/runoff/runoff_1981_05.nc

water_management:
  enabled: true
  demand:
    read_from_file: true
    path: ./input/demand/demand_1981_05.nc
  reservoirs:
    parameters:
      path: ./input/reservoirs/grand_reservoir_parameters.nc
    dependencies:
      path: ./input/reservoirs/grand_dependency_database.parquet
    streamflow:
      path: ./input/reservoirs/grand_average_monthly_flow.parquet
    demand:
      path: ./input/reservoirs/grand_average_monthly_demand.parquet
