name: windows

on: [pull_request]

jobs:
  build:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [windows-latest]

      env:
        OS: ${{ matrix.os }}
        PYTHON: '3.7'

      steps:

        - uses: actions/checkout@v1

        - name: Set up Python
          uses: actions/setup-python@master
          with:
            python-version: 3.7

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            curl -O https://download.lfd.uci.edu/pythonlibs/q4trcu4l/numpy-1.20.3+mkl-cp37-cp37m-win_amd64.whl
            pip install numpy-1.20.3+mkl-cp37-cp37m-win_amd64.whl
            curl -O https://download.lfd.uci.edu/pythonlibs/q4trcu4l/GDAL-3.3.0-cp37-cp37m-win_amd64.whl
            pip install GDAL-3.3.0-cp37-cp37m-win_amd64.whl
            curl -O https://download.lfd.uci.edu/pythonlibs/q4trcu4l/rasterio-1.2.4-cp37-cp37m-win_amd64.whl
            pip install rasterio-1.2.4-cp37-cp37m-win_amd64.whl
            pip install .

        - name: Test
          run: |
            pip install pytest
            pytest
