name: linux

on: [push]

jobs:
  build:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest]

      env:
        OS: ${{ matrix.os }}
        PYTHON: '3.7.2'

      steps:

        - uses: actions/checkout@v1

        - name: Set up Python
          uses: actions/setup-python@master
          with:
            python-version: 3.7.2

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .

        - name: Test and generate coverage report
          run: |
            pip install pytest
            pytest
