name: windows

on: [push]

jobs:
  build:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [windows-latest]

      env:
        OS: ${{ matrix.os }}
        PYTHON: '3.7'

      steps:

        - uses: actions/checkout@v1

        - name: Set up Python
          uses: actions/setup-python@master
          with:
            python-version: 3.7

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            curl https://download.lfd.uci.edu/pythonlibs/q4trcu4l/numpy-1.20.3+mkl-cp37-cp37m-win_amd64.whl --o np.whl
            pip install np.whl
            curl https://download.lfd.uci.edu/pythonlibs/q4trcu4l/GDAL-3.2.3-cp37-cp37m-win_amd64.whl --o gdal.whl
            pip install gdal.whl
            curl https://download.lfd.uci.edu/pythonlibs/q4trcu4l/rasterio-1.2.4-cp37-cp37m-win_amd64.whl --o rasterio.whl
            pip install rasterio.whl
            pip install .

        - name: Test and generate coverage report
          run: |
            pip install pytest
            pytest
