name: windows

#on: [push]
on: workflow_dispatch

jobs:
  build:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [windows-latest]

      env:
        OS: ${{ matrix.os }}
        PYTHON: '3.9'

      steps:

        - uses: actions/checkout@v1

        - name: Set up Python
          uses: actions/setup-python@master
          with:
            python-version: 3.9

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            curl -O https://download.lfd.uci.edu/pythonlibs/w4tscw6k/numpy-1.20.3+mkl-cp39-cp39-win_amd64.whl
            pip install numpy-1.20.3+mkl-cp39-cp39-win_amd64.whl
            curl -O https://download.lfd.uci.edu/pythonlibs/w4tscw6k/GDAL-3.3.0-cp39-cp39-win_amd64.whl
            pip install GDAL-3.3.0-cp39-cp39-win_amd64.whl
            curl -O https://download.lfd.uci.edu/pythonlibs/w4tscw6k/rasterio-1.2.4-cp39-cp39-win_amd64.whl
            pip install rasterio-1.2.4-cp39-cp39-win_amd64.whl
            pip install -r requirements.txt
            python setup.py install
            pip install numpy --upgrade
            pip install python-benedict --upgrade

        - name: Test and generate coverage report
          run: |
            pip install pytest
            pytest
